package de.cdelmonte.fds.datagenerator.orchestrator.model.actor;

public enum ClientPlatform {
  REGISTERED_FROM_WEB_DESKTOP, REGISTERED_FROM_WEB_MOBILE, REGISTERED_FROM_APPLICATION, ACTIVATED_FROM_WEB_DESKTOP, ACTIVATED_FROM_WEB_MOBILE, ACTIVATED_FROM_APPLICATION;
}
