server:
  port: 2673

logging:
  level:
    com.netflix: WARN
    de.cdelmonte: DEBUG
    org.springframework.web: WARN

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix.shareSecurityContext: true
feign.hystrix.enabled: false

spring.data.neo4j.username: neo4j
spring.data.neo4j.password: secret
spring.data.neo4j.uri: bolt://localhost:7687
